### ISSUE TITLE
{ range: '^0.0.0' } throws error

### ISSUE THREAD

**Issue by jlarmstrongiv** [rexxars/get-latest-version#1]
```
UnhandledPromiseRejectionWarning: Error: No version exists that satisfies "^0.0.0"
```

Hi 👋

Thanks for creating and open sourcing this helpful package!  I’m trying to use it in my [project](https://github.com/jlarmstrongiv/tfjs-node-lambda/blob/main/.github/actions/matrix/src/tensorflow/getTensorflow.ts#L21) to fetch all major versions of the @tensorflow/tfjs-node [npm](https://www.npmjs.com/package/@tensorflow/tfjs-node) package.

The package correctly gets the latest versions for `^1.0.0` and `^2.0.0` as `1.7.4` and `2.7.0` respectively.  

However, when I try fetching `^0.0.0`, the package can’t find `0.3.2`.

**Comment by rexxars** [comment]
That's technically correct - according to the semver specification, `0.x` ranges are treated differently. `^0.3.0` would match `0.3.2`, as far as I can remember, but `^0.1.0` does not. Anything above `1.x` works as you would expect. Here's [one of many](https://github.com/semver/semver/issues/221) threads discussing this.

**Comment by jlarmstrongiv** [comment]
Wow, I never would’ve guessed.  Thank you!
